# Generated by Django 3.0.7 on 2020-09-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=100)),
                ('Lname', models.CharField(max_length=500)),
                ('Age', models.IntegerField()),
                ('sex', models.CharField(max_length=200)),
                ('Contact', models.CharField(max_length=1000)),
                ('Email', models.EmailField(max_length=100)),
                ('Address', models.TextField()),
                ('city', models.CharField(max_length=400)),
                ('state', models.CharField(max_length=500)),
                ('reason', models.TextField()),
                ('medicine', models.TextField()),
            ],
            options={
                'db_table': 'patientinfo',
            },
        ),
    ]
