# Generated by Django 3.0.7 on 2020-09-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='medicine',
            field=models.TextField(blank=True, default=''),
        ),
    ]
