# Generated by Django 3.0.7 on 2020-09-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0002_auto_20200912_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='report',
            field=models.TextField(default=''),
        ),
    ]
