# Generated by Django 3.0.7 on 2020-09-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0003_patientinfo_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='report',
            field=models.TextField(blank=True, default=''),
        ),
    ]
