# Generated by Django 3.0.7 on 2020-09-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0004_auto_20200912_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='patient',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='tablet',
            field=models.TextField(default=''),
        ),
    ]
