# Generated by Django 3.0.7 on 2020-09-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0005_auto_20200912_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='tablet',
            field=models.TextField(blank=True, default=''),
        ),
    ]
