# Generated by Django 3.0.7 on 2020-09-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0006_auto_20200913_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='patient',
            field=models.TextField(blank=True, default=''),
        ),
    ]
